# 01 Pandas — Basics + Revision Practice Sheet

This sheet starts from the **Pandas basics** and gradually moves toward practical data-analysis exercises.

## How to use this notebook
1. Read the short revision block before each section.
2. Try every exercise yourself first.
3. Do not look for a solution immediately.
4. Use the later sections to combine multiple Pandas concepts.
5. The goal is to build enough fluency for **data analysis / AIML work**.

---

## Revision map

This sheet revises the Pandas topics that are repeatedly useful in practical datasets:

- Series and DataFrame
- Creating DataFrames
- `shape`, `columns`, `index`, `dtypes`, `info()`
- Selecting columns and rows
- `loc` and `iloc`
- Boolean filtering
- `isin()`
- Sorting
- `value_counts()`
- `nunique()`
- Missing-value detection
- `isna()` / `notna()`
- `fillna()` / `dropna()`
- Duplicates
- `describe()`
- `groupby()`
- Aggregation
- `agg()`
- Creating/modifying columns
- `astype()`
- String operations
- Basic date operations
- `reset_index()`
- Combining practical operations

# 1. Pandas Basics

### Quick revision

Pandas mainly gives us two structures:

- **Series** → one-dimensional labeled data
- **DataFrame** → two-dimensional table

Important imports:

```python
import pandas as pd
import numpy as np
```

Common constructors:

```python
pd.Series(...)
pd.DataFrame(...)
```

### Practice
Create:
1. A Series containing 5 student marks.
2. A DataFrame containing 5 students with columns:
   - `name`
   - `age`
   - `branch`
   - `marks`

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Write your code here
marks = [87,67,89,78,67]
pd.Series(marks)

0    87
1    67
2    89
3    78
4    67
dtype: int64

In [3]:
students = {
    "name": ["Luffy", "Zoro", "Nami", "Sanji", "Robin", "Usopp", "Franky", "Brook"],
    "age": [18, 19, 18, 20, 19, 18, 21, 20],
    "branch": ["CSE", "IT", "ECE", "CSE", "IT", "CSE", "ME", "ECE"],
    "marks": [87, 92, 78, 85, 95, 67, 74, 81]
}

data = pd.DataFrame(students)
data

     name  age branch  marks
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
2    Nami   18    ECE     78
3   Sanji   20    CSE     85
4   Robin   19     IT     95
5   Usopp   18    CSE     67
6  Franky   21     ME     74
7   Brook   20    ECE     81

# 2. Inspecting a DataFrame

### Quick revision

Before analyzing a dataset, inspect its structure.

Useful operations:

- `data.shape`
- `data.columns`
- `data.index`
- `data.dtypes`
- `data.info()`
- `data.head()`
- `data.tail()`
- `data.sample()`

### Practice

Using your DataFrame:

1. Find the number of rows and columns.
2. Display all column names.
3. Display the data types.
4. Display the first 3 rows.
5. Display the last 2 rows.
6. Display 3 random rows.

In [4]:
# Write your code here
print(data.shape)
print(data.columns)
print(data.dtypes)
print(data.head(3))
print(data.tail(2))
print(data.sample(3))

(8, 4)
Index(['name', 'age', 'branch', 'marks'], dtype='str')
name        str
age       int64
branch      str
marks     int64
dtype: object
    name  age branch  marks
0  Luffy   18    CSE     87
1   Zoro   19     IT     92
2   Nami   18    ECE     78
     name  age branch  marks
6  Franky   21     ME     74
7   Brook   20    ECE     81
     name  age branch  marks
4   Robin   19     IT     95
5   Usopp   18    CSE     67
6  Franky   21     ME     74

# 3. Selecting Columns

### Quick revision

Single column:

```python
data["marks"]
```

Multiple columns:

```python
data[["name", "marks"]]
```

### Practice

1. Select only the `name` column.
2. Select `name` and `marks`.
3. Select `age`, `branch`, and `marks`.
4. Find the maximum marks from the selected marks column.

In [5]:
# Write your code here
print(data["name"])
print(data[["name","marks"]])
print(data[["age","branch","marks"]])
print(data["marks"].max())

0     Luffy
1      Zoro
2      Nami
3     Sanji
4     Robin
5     Usopp
6    Franky
7     Brook
Name: name, dtype: str
     name  marks
0   Luffy     87
1    Zoro     92
2    Nami     78
3   Sanji     85
4   Robin     95
5   Usopp     67
6  Franky     74
7   Brook     81
   age branch  marks
0   18    CSE     87
1   19     IT     92
2   18    ECE     78
3   20    CSE     85
4   19     IT     95
5   18    CSE     67
6   21     ME     74
7   20    ECE     81
95

# 4. Row Selection — `loc` and `iloc`

### Quick revision

- `iloc` → position-based selection
- `loc` → label/condition-based selection

Examples:

```python
data.iloc[0]
data.iloc[0:3]
data.loc[data["marks"] > 80]
```

### Practice

1. Select the first row using `iloc`.
2. Select the first 3 rows.
3. Select rows 2–4 and only `name` + `marks`.
4. Select all students whose marks are greater than 70.
5. Select students from the `CSE` branch.

In [6]:
# Write your code here
print(data.iloc[0])
print(data.iloc[0:3])
print(data[["name","marks"]].iloc[2:5])
print(data.loc[data["marks"]>70])
print(data.loc[data["branch"]=="CSE"])

name      Luffy
age          18
branch      CSE
marks        87
Name: 0, dtype: object
    name  age branch  marks
0  Luffy   18    CSE     87
1   Zoro   19     IT     92
2   Nami   18    ECE     78
    name  marks
2   Nami     78
3  Sanji     85
4  Robin     95
     name  age branch  marks
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
2    Nami   18    ECE     78
3   Sanji   20    CSE     85
4   Robin   19     IT     95
6  Franky   21     ME     74
7   Brook   20    ECE     81
    name  age branch  marks
0  Luffy   18    CSE     87
3  Sanji   20    CSE     85
5  Usopp   18    CSE     67

# 5. Boolean Filtering

### Quick revision

Comparison operators:

```python
>
<
>=
<=
==
!=
```

Combine conditions:

```python
(data["marks"] >= 70) & (data["age"] > 18)
```

Use `|` for OR.

### Practice

1. Students with marks >= 80.
2. Students with marks between 60 and 80.
3. CSE students with marks >= 70.
4. Students who are NOT from CSE.
5. Students older than 18 OR marks above 85.
6. Use `isin()` to select students from CSE or IT.

In [7]:
# Write your code here
print(data.loc[data["marks"]>=80])
print(data.loc[(data["marks"]>60) & (data["marks"]<80)])
print(data.loc[(data["marks"]>=70) & (data["branch"]=="CSE")])
print(data.loc[data["branch"]!="CSE"])
print(data.loc[(data["age"]>18) & (data["marks"]>85)])
data[data["branch"].isin(["CSE", "IT"])]

    name  age branch  marks
0  Luffy   18    CSE     87
1   Zoro   19     IT     92
3  Sanji   20    CSE     85
4  Robin   19     IT     95
7  Brook   20    ECE     81
     name  age branch  marks
2    Nami   18    ECE     78
5   Usopp   18    CSE     67
6  Franky   21     ME     74
    name  age branch  marks
0  Luffy   18    CSE     87
3  Sanji   20    CSE     85
     name  age branch  marks
1    Zoro   19     IT     92
2    Nami   18    ECE     78
4   Robin   19     IT     95
6  Franky   21     ME     74
7   Brook   20    ECE     81
    name  age branch  marks
1   Zoro   19     IT     92
4  Robin   19     IT     95

    name  age branch  marks
0  Luffy   18    CSE     87
1   Zoro   19     IT     92
3  Sanji   20    CSE     85
4  Robin   19     IT     95
5  Usopp   18    CSE     67

# 6. Sorting

### Quick revision

```python
data.sort_values("marks")
data.sort_values("marks", ascending=False)
```

Multiple columns can also be sorted.

### Practice

1. Sort students by marks from low to high.
2. Sort marks from high to low.
3. Sort by `branch`, then by marks descending.
4. Find the top 3 students by marks.

In [8]:
# Write your code here
print(data.sort_values("marks"))
print(data.sort_values("marks",ascending=False))
print(data.sort_values(["branch","marks"],ascending=[True,False]))
print(data.sort_values(["marks"],ascending=False).head(3))

     name  age branch  marks
5   Usopp   18    CSE     67
6  Franky   21     ME     74
2    Nami   18    ECE     78
7   Brook   20    ECE     81
3   Sanji   20    CSE     85
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
4   Robin   19     IT     95
     name  age branch  marks
4   Robin   19     IT     95
1    Zoro   19     IT     92
0   Luffy   18    CSE     87
3   Sanji   20    CSE     85
7   Brook   20    ECE     81
2    Nami   18    ECE     78
6  Franky   21     ME     74
5   Usopp   18    CSE     67
     name  age branch  marks
0   Luffy   18    CSE     87
3   Sanji   20    CSE     85
5   Usopp   18    CSE     67
7   Brook   20    ECE     81
2    Nami   18    ECE     78
4   Robin   19     IT     95
1    Zoro   19     IT     92
6  Franky   21     ME     74
    name  age branch  marks
4  Robin   19     IT     95
1   Zoro   19     IT     92
0  Luffy   18    CSE     87

# 7. Frequency Analysis

### Quick revision

Very useful functions:

```python
data["branch"].value_counts()
data["branch"].nunique()
data.nunique()
```

- `value_counts()` → frequency of each value
- `nunique()` → number of unique values

### Practice

1. Count students in each branch.
2. Find the number of unique branches.
3. Find unique counts for every column.
4. Find the most common branch.
5. Find the least common branch.

In [9]:
print(data["branch"].value_counts())
print(data["branch"].unique())
col = data.columns
print(data[col].nunique())

branch
CSE    3
IT     2
ECE    2
ME     1
Name: count, dtype: int64
<StringArray>
['CSE', 'IT', 'ECE', 'ME']
Length: 4, dtype: str
name      8
age       4
branch    4
marks     8
dtype: int64

# 8. Missing Values

### Quick revision

Important checks:

```python
data.isna()
data.isna().sum()
data.notna().sum()
data.isna().any()
```

For a specific column:

```python
data["marks"].isna().sum()
```

### Practice

Create a small DataFrame containing some missing values and:

1. Count missing values in every column.
2. Find which columns contain missing values.
3. Find the total number of missing cells.
4. Find rows where `marks` is missing.
5. Find rows where `marks` is NOT missing.

In [10]:
print(data.isna())
print((data.isna().sum()))
print(data["marks"].isna().sum())
print(data["marks"].notna())

    name    age  branch  marks
0  False  False   False  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False
4  False  False   False  False
5  False  False   False  False
6  False  False   False  False
7  False  False   False  False
name      0
age       0
branch    0
marks     0
dtype: int64
0
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: marks, dtype: bool

# 9. Handling Missing Values

### Quick revision

Common approaches:

```python
data.dropna()
data.fillna(value)
data["marks"].fillna(data["marks"].mean())
```

**Important:** Do not blindly replace every missing value with the mean. The correct method depends on the meaning of the column.

### Practice

1. Drop rows containing missing values.
2. Fill a numeric column's missing values with its mean.
3. Fill a categorical column's missing values with `"Unknown"`.
4. Compare the number of rows before and after `dropna()`.
5. Explain in a Markdown cell which method is more appropriate for each column.

In [11]:
# Write your code here
print(data.dropna())
print(data.fillna(data.mean))
print(data[col].fillna("Unkown"))

     name  age branch  marks
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
2    Nami   18    ECE     78
3   Sanji   20    CSE     85
4   Robin   19     IT     95
5   Usopp   18    CSE     67
6  Franky   21     ME     74
7   Brook   20    ECE     81
     name  age branch  marks
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
2    Nami   18    ECE     78
3   Sanji   20    CSE     85
4   Robin   19     IT     95
5   Usopp   18    CSE     67
6  Franky   21     ME     74
7   Brook   20    ECE     81
     name  age branch  marks
0   Luffy   18    CSE     87
1    Zoro   19     IT     92
2    Nami   18    ECE     78
3   Sanji   20    CSE     85
4   Robin   19     IT     95
5   Usopp   18    CSE     67
6  Franky   21     ME     74
7   Brook   20    ECE     81

# 10. Duplicates

### Quick revision

Useful operations:

```python
data.duplicated()
data.duplicated().sum()
data.drop_duplicates()
```

### Practice

1. Create a DataFrame containing duplicate rows.
2. Count duplicate rows.
3. Display only duplicate rows.
4. Remove duplicates.
5. Compare the shape before and after removing duplicates.

### Check yourself

A common mistake is confusing:

```python
data.drop_duplicates()
```

with:

```python
data.duplicated()
```

The first returns a cleaned DataFrame; the second identifies duplicates.

In [12]:
students = {
    "name": ["Luffy", "Zoro", "Luffy", "Nami", "Zoro", "Sanji"],
    "branch": ["CSE", "IT", "CSE", "ECE", "IT", "CSE"],
    "age": [18, 19, 18, 20,  18, 20],
    "marks": [87, 92, 87, 78, 92, 85]
}

data = pd.DataFrame(students)

print(data.duplicated().count())
print(data.iloc[data.duplicated()])
drop = data.drop_duplicates()
print(drop)
print(f"{data.shape} before drop {drop.shape} after drop")

6
    name branch  age  marks
2  Luffy    CSE   18     87
    name branch  age  marks
0  Luffy    CSE   18     87
1   Zoro     IT   19     92
3   Nami    ECE   20     78
4   Zoro     IT   18     92
5  Sanji    CSE   20     85
(6, 4) before drop (5, 4) after drop

# 11. Descriptive Statistics

### Quick revision

```python
data.describe()
```

Important statistics:

- count
- mean
- std
- min
- 25%
- 50% (median)
- 75%
- max

Other useful operations:

```python
data["marks"].mean()
data["marks"].median()
data["marks"].std()
data["marks"].min()
data["marks"].max()
```

### Practice

1. Generate descriptive statistics.
2. Find the average marks.
3. Find the median marks.
4. Find the standard deviation.
5. Find the minimum and maximum.
6. Compare mean and median and write what you observe.

In [13]:
print(data.describe())
print(data["marks"].mean())
print(data["marks"].median())
print(data["marks"].std())
print(data["marks"].min())
print(data["marks"].max())
print(f"{data.mean}-{data.median}")

             age      marks
count   6.000000   6.000000
mean   18.833333  86.833333
std     0.983192   5.192944
min    18.000000  78.000000
25%    18.000000  85.500000
50%    18.500000  87.000000
75%    19.750000  90.750000
max    20.000000  92.000000
86.83333333333333
87.0
5.192943930629972
78
92
<bound method DataFrame.mean of     name branch  age  marks
0  Luffy    CSE   18     87
1   Zoro     IT   19     92
2  Luffy    CSE   18     87
3   Nami    ECE   20     78
4   Zoro     IT   18     92
5  Sanji    CSE   20     85>-<bound method DataFrame.median of     name branch  age  marks
0  Luffy    CSE   18     87
1   Zoro     IT   19     92
2  Luffy    CSE   18     87
3   Nami    ECE   20     78
4   Zoro     IT   18     92
5  Sanji    CSE   20     85>

# 12. Creating and Modifying Columns

### Quick revision

You can create derived columns:

```python
data["passed"] = data["marks"] >= 40
```

You can also calculate from existing columns.

### Practice

Add:

1. `passed` → True if marks >= 40.
2. `marks_percentage` → convert marks out of 100 if your dataset uses another scale.
3. `performance` with categories such as `"High"`, `"Medium"`, `"Low"`.
4. Modify one existing column and verify the result.

In [14]:
for i in data["marks"]:
    if i >= 40:
        data["passed"] = True
    else:
        data["passed"] = False
    
data

    name branch  age  marks  passed
0  Luffy    CSE   18     87    True
1   Zoro     IT   19     92    True
2  Luffy    CSE   18     87    True
3   Nami    ECE   20     78    True
4   Zoro     IT   18     92    True
5  Sanji    CSE   20     85    True

# 13. Data Types

### Quick revision

Inspect:

```python
data.dtypes
```

Convert:

```python
data["age"] = data["age"].astype(int)
```

Use `astype()` carefully. Conversion can fail when values are incompatible.

### Practice

1. Identify numeric and non-numeric columns.
2. Convert a suitable column to integer.
3. Convert a suitable categorical column to `category`.
4. Check the data types again.

In [15]:
print(data.dtypes)
data["age"] = data["age"].astype(int)
data

name        str
branch      str
age       int64
marks     int64
passed     bool
dtype: object

    name branch  age  marks  passed
0  Luffy    CSE   18     87    True
1   Zoro     IT   19     92    True
2  Luffy    CSE   18     87    True
3   Nami    ECE   20     78    True
4   Zoro     IT   18     92    True
5  Sanji    CSE   20     85    True

# 14. String Operations

### Quick revision

For text columns, Pandas provides `.str`:

```python
data["name"].str.upper()
data["name"].str.lower()
data["name"].str.strip()
data["name"].str.contains("a")
```

### Practice

1. Convert names to uppercase.
2. Convert names to lowercase.
3. Remove extra spaces.
4. Find names containing the letter `"a"`.
5. Create a new column containing the length of each name.

In [16]:
print(data["name"].str.upper())
print(data["name"].str.lower())
print(data["name"].str.strip())
print(data["name"].str.contains("a"))
data["length"] = data["name"].str.len()
print(data)

0    LUFFY
1     ZORO
2    LUFFY
3     NAMI
4     ZORO
5    SANJI
Name: name, dtype: str
0    luffy
1     zoro
2    luffy
3     nami
4     zoro
5    sanji
Name: name, dtype: str
0    Luffy
1     Zoro
2    Luffy
3     Nami
4     Zoro
5    Sanji
Name: name, dtype: str
0    False
1    False
2    False
3     True
4    False
5     True
Name: name, dtype: bool
    name branch  age  marks  passed  length
0  Luffy    CSE   18     87    True       5
1   Zoro     IT   19     92    True       4
2  Luffy    CSE   18     87    True       5
3   Nami    ECE   20     78    True       4
4   Zoro     IT   18     92    True       4
5  Sanji    CSE   20     85    True       5

# 15. GroupBy — Core Data Analysis Skill

### Quick revision

`groupby()` is one of the most important Pandas operations for analytics.

Pattern:

```python
data.groupby("branch")["marks"].mean()
```

Other aggregations:

```python
.sum()
.mean()
.min()
.max()
.count()
```

### Practice

For a student dataset:

1. Find average marks by branch.
2. Find maximum marks by branch.
3. Find minimum marks by branch.
4. Count students by branch.
5. Find average age by branch.
6. Find the total marks by branch.

In [17]:
print(data.groupby("branch")["marks"].mean())
print(data.groupby("branch")["marks"].max())
print(data.groupby("branch")["marks"].min())
print(data.groupby("branch")["age"].mean())
print(data.groupby("branch")["marks"].sum())

branch
CSE    86.333333
ECE    78.000000
IT     92.000000
Name: marks, dtype: float64
branch
CSE    87
ECE    78
IT     92
Name: marks, dtype: int64
branch
CSE    85
ECE    78
IT     92
Name: marks, dtype: int64
branch
CSE    18.666667
ECE    20.000000
IT     18.500000
Name: age, dtype: float64
branch
CSE    259
ECE     78
IT     184
Name: marks, dtype: int64

# 16. `groupby()` + `agg()` — Revision

### Quick revision

Multiple statistics can be calculated together:

```python
data.groupby("branch")["marks"].agg(["mean", "min", "max", "count"])
```

### Practice

Create a branch-wise summary containing:

- number of students
- average marks
- minimum marks
- maximum marks
- median marks

Then sort the result by average marks.

In [18]:
print(data.groupby("branch")["name"].count().agg(["mean","min","max","count"]))
print(data.groupby("branch")["marks"].mean())
print(data.groupby("branch")["marks"].max())
print(data.groupby("branch")["marks"].min())
print(data.groupby("branch")["marks"].std())

mean     2.0
min      1.0
max      3.0
count    3.0
Name: name, dtype: float64
branch
CSE    86.333333
ECE    78.000000
IT     92.000000
Name: marks, dtype: float64
branch
CSE    87
ECE    78
IT     92
Name: marks, dtype: int64
branch
CSE    85
ECE    78
IT     92
Name: marks, dtype: int64
branch
CSE    1.154701
ECE         NaN
IT     0.000000
Name: marks, dtype: float64

# 17. Index Handling

### Quick revision

Useful operations:

```python
data.reset_index()
data.set_index("name")
```

Remember: `groupby()` can return a grouped column as an index.

### Practice

1. Perform a groupby operation.
2. Reset the resulting index.
3. Set a suitable column as the index.
4. Reset it back to the default index.

In [19]:
index = data.set_index(["name"])
print(index)
index = data.reset_index()
print(index)
index = data.set_index(["name"])
print(index)
index = data.reset_index()
print(index)

      branch  age  marks  passed  length
name
Luffy    CSE   18     87    True       5
Zoro      IT   19     92    True       4
Luffy    CSE   18     87    True       5
Nami     ECE   20     78    True       4
Zoro      IT   18     92    True       4
Sanji    CSE   20     85    True       5
   index   name branch  age  marks  passed  length
0      0  Luffy    CSE   18     87    True       5
1      1   Zoro     IT   19     92    True       4
2      2  Luffy    CSE   18     87    True       5
3      3   Nami    ECE   20     78    True       4
4      4   Zoro     IT   18     92    True       4
5      5  Sanji    CSE   20     85    True       5
      branch  age  marks  passed  length
name
Luffy    CSE   18     87    True       5
Zoro      IT   19     92    True       4
Luffy    CSE   18     87    True       5
Nami     ECE   20     78    True       4
Zoro      IT   18     92    True       4
Sanji    CSE   20     85    True       5
   index   name branch  age  marks  passed  length
0      0  Luffy    CSE   18     87    True       5
1      1   Zoro     IT   19     92    True       4
2      2  Luffy    CSE   18     87    True       5
3      3   Nami    ECE   20     78    True       4
4      4   Zoro     IT   18     92    True       4
5      5  Sanji    CSE   20     85    True       5

# 18. Mini Dataset Analysis — Combine Everything

Create or load a dataset with at least these columns:

- `name`
- `branch`
- `college_tier`
- `cgpa`
- `backlogs`
- `coding_skills`
- `internships`
- `projects_count`
- `placement_status`
- `salary_package_lpa`

## Tasks

### A. Structure
1. Check shape.
2. Check columns.
3. Check dtypes.
4. Check missing values.

### B. Quality
5. Check duplicate rows.
6. Check unique values.
7. Check invalid/unusual values.

### C. Statistics
8. Generate descriptive statistics.
9. Find average CGPA.
10. Find median coding skill.
11. Find maximum salary package.

### D. Categories
12. Count students by branch.
13. Count placed vs not placed students.
14. Count students by college tier.

### E. Filtering
15. Find students with CGPA > 8.
16. Find students with no backlogs and at least one internship.
17. Find students who are placed and have coding skills > 7.

### F. Grouping
18. Find placement count by branch.
19. Find average CGPA by branch.
20. Find average salary among placed students by branch.
21. Find placement count by college tier.

### G. Final analysis
22. Identify which branch has the highest placement count.
23. Identify which college tier has the highest placement rate.
24. Compare placed vs unplaced students.
25. Write **5 observations** from the dataset in Markdown.

In [20]:
df = pd.read_csv("student.csv")
df

,student_id,name,branch,college_tier,cgpa,backlogs,coding_skills,internships,projects_count,placement_status,salary_package_lpa
0,STU00001,Himmel,CSE,Tier-3,6.04,1,6.7,1,3,0,NaN
1,STU00002,Gojo,CE,Tier-3,7.39,1,4.5,2,1,1,6.65
2,STU00003,Robin,ME,Tier-3,7.78,0,3.9,0,3,1,9.17
3,STU00004,Bokuto,EE,Tier-2,6.83,0,7.8,1,1,1,10.16
4,STU00005,Todoroki,EE,Tier-2,5.85,0,8.8,0,1,1,9.40
...,...,...,...,...,...,...,...,...,...,...,...
49995,STU49996,Megumi Fushiguro,EE,Tier-1,5.88,0,3.2,0,4,1,8.91
49996,STU49997,Jiraiya,Chemical,Tier-3,5.96,0,6.2,1,3,1,6.38
49997,STU49998,Escanor,IT,Tier-2,6.52,0,3.5,0,4,0,NaN
49998,STU49999,Frieren,ECE,Tier-2,6.93,0,4.5,0,2,1,8.63
49999,STU50000,Igris,ME,Tier-2,6.75,0,6.2,1,5,1,10.44

In [21]:
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.isna())

(50000, 11)
Index(['student_id', 'name', 'branch', 'college_tier', 'cgpa', 'backlogs',
       'coding_skills', 'internships', 'projects_count', 'placement_status',
       'salary_package_lpa'],
      dtype='str')
student_id                str
name                      str
branch                    str
college_tier              str
cgpa                  float64
backlogs                int64
coding_skills         float64
internships             int64
projects_count          int64
placement_status        int64
salary_package_lpa    float64
dtype: object
       student_id   name  branch  college_tier   cgpa  backlogs  \
0           False  False   False         False  False     False
1           False  False   False         False  False     False
2           False  False   False         False  False     False
3           False  False   False         False  False     False
4           False  False   False         False  False     False
...           ...    ...     ...           ...    ...       ...
49995       False  False   False         False  False     False
49996       False  False   False         False  False     False
49997       False  False   False         False  False     False
49998       False  False   False         False  False     False
49999       False  False   False         False  False     False

       coding_skills  internships  projects_count  placement_status  \
0              False        False           False             False
1              False        False           False             False
2              False        False           False             False
3              False        False           False             False
4              False        False           False             False
...              ...          ...             ...               ...
49995          False        False           False             False
49996          False        False           False             False
49997          False        False           False             False
49998          False        False           False             False
49999          False        False           False             False

       salary_package_lpa
0                    True
1                   False
2                   False
3                   False
4                   False
...                   ...
49995               False
49996               False
49997                True
49998               False
49999               False

[50000 rows x 11 columns]

In [22]:
print(df.duplicated())
print(df.nunique())

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Length: 50000, dtype: bool
student_id            50000
name                    178
branch                    7
college_tier              3
cgpa                    582
backlogs                  4
coding_skills            91
internships               4
projects_count            6
placement_status          2
salary_package_lpa     1237
dtype: int64

In [ ]:
print(df.describe())
print(df["cgpa"].mean())
print(df["coding_skills"].mean())
print(df["salary_package_lpa"].mean())

               cgpa      backlogs  coding_skills   internships  \
count  50000.000000  50000.000000   50000.000000  50000.000000
mean       7.193805      0.630940       6.003448      0.798380
std        0.902579      0.808077       1.490466      0.870968
min        4.000000      0.000000       1.000000      0.000000
25%        6.580000      0.000000       5.000000      0.000000
50%        7.190000      0.000000       6.000000      1.000000
75%        7.800000      1.000000       7.000000      1.000000
max       10.000000      3.000000      10.000000      3.000000

       projects_count  placement_status  salary_package_lpa
count    50000.000000      50000.000000        28789.000000
mean         2.398800          0.575780           10.291773
std          1.236313          0.494229            2.083161
min          0.000000          0.000000            2.500000
25%          2.000000          0.000000            8.860000
50%          2.000000          1.000000           10.230000
75%          3.000000          1.000000           11.680000
max          5.000000          1.000000           18.610000
7.1938052
6.003448000000001
10.291772899371287

In [51]:
print(df["branch"].count())
place = 0
not_place = 0 
for i  in df["placement_status"]:
    if i == 0:
        not_place+=1
    elif i == 1:
        place+=1
print(f"No of place student {place} No of not place student {not_place}")
df.groupby("college_tier")["name"].count()

50000
No of place student 28789 No of not place student 21211

college_tier
Tier-1     7425
Tier-2    19978
Tier-3    22597
Name: name, dtype: int64

In [ ]:
print(df.loc[df["cgpa"]>8])
print(df.loc[(df["backlogs"]>0) & (df["internships"]>1)])
print(df.loc[(df["placement_status"]==1) & (df["coding_skills"]>7)])

      student_id        name    branch college_tier  cgpa  backlogs  \
19      STU00020  Momo Ayase        EE       Tier-3  8.14         2
20      STU00021      Megumi        EE       Tier-3  9.42         0
23      STU00024      Kirito  Chemical       Tier-2  8.22         1
26      STU00027        Bond       ECE       Tier-3  8.82         0
35      STU00036    Ishikawa       CSE       Tier-3  8.87         1
...          ...         ...       ...          ...   ...       ...
49983   STU49984        Levi        CE       Tier-1  8.12         0
49985   STU49986   All Might       ECE       Tier-2  9.19         1
49986   STU49987      Jotaro  Chemical       Tier-2  8.02         0
49989   STU49990    Kenpachi        IT       Tier-3  8.04         0
49992   STU49993       Armin        CE       Tier-3  8.82         0

       coding_skills  internships  projects_count  placement_status  \
19               4.4            0               3                 0
20               9.6            0               1                 1
23               9.4            2               3                 1
26               6.8            1               2                 1
35               5.3            1               3                 0
...              ...          ...             ...               ...
49983            4.6            1               3                 1
49985            6.3            0               0                 1
49986            6.3            0               2                 1
49989            6.2            1               3                 1
49992            8.5            2               2                 1

       salary_package_lpa
19                    NaN
20                  10.91
23                  10.87
26                   8.99
35                    NaN
...                   ...
49983               13.28
49985               12.18
49986                9.44
49989               11.95
49992                8.95

[9279 rows x 11 columns]
      student_id       name    branch college_tier  cgpa  backlogs  \
1       STU00002       Gojo        CE       Tier-3  7.39         1
5       STU00006     Frieza  Chemical       Tier-2  6.42         1
8       STU00009      Isagi        IT       Tier-3  6.14         2
23      STU00024     Kirito  Chemical       Tier-2  8.22         1
37      STU00038  Cha Haein        CE       Tier-3  7.41         1
...          ...        ...       ...          ...   ...       ...
49936   STU49937       Giyu       ECE       Tier-3  7.06         1
49958   STU49959       Zoro        IT       Tier-2  6.52         1
49968   STU49969        Rem        CE       Tier-3  7.29         2
49969   STU49970      Gaara  Chemical       Tier-1  7.65         1
49977   STU49978     Ichigo       CSE       Tier-2  6.92         1

       coding_skills  internships  projects_count  placement_status  \
1                4.5            2               1                 1
5                3.8            2               1                 0
8                5.3            2               1                 1
23               9.4            2               3                 1
37               5.7            2               4                 0
...              ...          ...             ...               ...
49936            5.8            2               4                 1
49958            5.2            2               4                 0
49968            4.4            2               4                 1
49969            6.5            3               4                 1
49977            8.1            3               2                 1

       salary_package_lpa
1                    6.65
5                     NaN
8                    9.29
23                  10.87
37                    NaN
...                   ...
49936               10.25
49958                 NaN
49968               11.09
49969               14.14
49977               13.75

[4520 rows x 11 columns]
      student_id      name    branch college_tier  cgpa  backlogs  \
3       STU00004    Bokuto        EE       Tier-2  6.83         0
4       STU00005  Todoroki        EE       Tier-2  5.85         0
20      STU00021    Megumi        EE       Tier-3  9.42         0
23      STU00024    Kirito  Chemical       Tier-2  8.22         1
34      STU00035    Trunks  Chemical       Tier-1  6.91         0
...          ...       ...       ...          ...   ...       ...
49964   STU49965      Ryuk        CE       Tier-3  7.66         2
49970   STU49971  Beatrice       CSE       Tier-3  6.08         0
49977   STU49978    Ichigo       CSE       Tier-2  6.92         1
49979   STU49980    Bokuto       CSE       Tier-1  5.30         0
49992   STU49993     Armin        CE       Tier-3  8.82         0

       coding_skills  internships  projects_count  placement_status  \
3                7.8            1               1                 1
4                8.8            0               1                 1
20               9.6            0               1                 1
23               9.4            2               3                 1
34               8.1            0               1                 1
...              ...          ...             ...               ...
49964            7.2            1               2                 1
49970            8.8            1               0                 1
49977            8.1            3               2                 1
49979            8.6            0               4                 1
49992            8.5            2               2                 1

       salary_package_lpa
3                   10.16
4                    9.40
20                  10.91
23                  10.87
34                  11.09
...                   ...
49964                8.79
49970               11.76
49977               13.75
49979               12.65
49992                8.95

[8253 rows x 11 columns]

In [79]:
print(df.groupby("branch")["placement_status"].sum())
print(df.groupby("branch")["cgpa"].mean())
print(df.groupby("branch")["salary_package_lpa"].mean())
print(df.groupby("college_tier")["placement_status"].sum())

branch
CE          4188
CSE         4166
Chemical    4064
ECE         4048
EE          4100
IT          4161
ME          4062
Name: placement_status, dtype: int64
branch
CE          7.197325
CSE         7.190563
Chemical    7.176475
ECE         7.188514
EE          7.219076
IT          7.180924
ME          7.203647
Name: cgpa, dtype: float64
branch
CE           9.893374
CSE         11.163805
Chemical     9.923354
ECE          9.953253
EE          10.000073
IT          11.142882
ME           9.936701
Name: salary_package_lpa, dtype: float64
college_tier
Tier-1     4717
Tier-2    11614
Tier-3    12458
Name: placement_status, dtype: int64

In [113]:
print(df.groupby("college_tier")["placement_status"].sum().max())
# df.loc[df.groupby("college_tier")["placement_status"].sum() == df.groupby("college_tier")["placement_status"].sum().max()]
print(df.groupby("branch")["cgpa"].mean())
print(df.groupby("branch")["salary_package_lpa"].mean())
print(df.groupby("placement_status")["college_tier"].count())
place = 0
not_place = 0 
for i  in df["placement_status"]:
    if i == 0:
        not_place+=1
    elif i == 1:
        place+=1
print(f"No of place student {place} \nNo of not place student {not_place}")

12458
branch
CE          7.197325
CSE         7.190563
Chemical    7.176475
ECE         7.188514
EE          7.219076
IT          7.180924
ME          7.203647
Name: cgpa, dtype: float64
branch
CE           9.893374
CSE         11.163805
Chemical     9.923354
ECE          9.953253
EE          10.000073
IT          11.142882
ME           9.936701
Name: salary_package_lpa, dtype: float64
placement_status
0    21211
1    28789
Name: college_tier, dtype: int64
No of place student 28789
No of not place student 21211

# 19. Challenge — No Step-by-Step Hints

Use a larger dataset if available.

Answer these questions using Pandas only:

1. Which 5 branches have the highest number of students?
2. What percentage of students are placed?
3. What percentage are unplaced?
4. What is the average CGPA of placed students?
5. What is the average CGPA of unplaced students?
6. Which branch has the highest placement rate?
7. Which college tier has the highest placement rate?
8. Among placed students, which group has the highest average salary?
9. Does having more internships appear associated with higher placement?
10. Does the number of projects appear associated with placement?
11. Compare average coding skill for placed vs unplaced students.
12. Produce one final summary DataFrame containing the most important metrics.

**Rule:** Try to solve this without copying previous cells. The point is to test whether you actually remember the operations.

In [ ]:
print(df["branch"].value_counts())
print(int(df.sum()))

AttributeError: 'Series' object has no attribute 'sort_value'

# 20. Final Revision Checklist

Before moving to the next Pandas sheet, make sure you can explain and use:

### Basics
- [ ] Series
- [ ] DataFrame
- [ ] DataFrame creation
- [ ] `head()`, `tail()`, `sample()`
- [ ] `shape`, `columns`, `index`, `dtypes`, `info()`

### Selection
- [ ] Column selection
- [ ] Multiple-column selection
- [ ] `loc`
- [ ] `iloc`
- [ ] Boolean filtering
- [ ] `isin()`

### Data inspection
- [ ] `value_counts()`
- [ ] `nunique()`
- [ ] `describe()`
- [ ] `isna()`
- [ ] `notna()`

### Data cleaning
- [ ] Missing-value handling
- [ ] Duplicates
- [ ] `drop_duplicates()`
- [ ] `astype()`

### Analysis
- [ ] Sorting
- [ ] Creating columns
- [ ] String operations
- [ ] `groupby()`
- [ ] Aggregation
- [ ] `agg()`
- [ ] `reset_index()`

### Practical thinking
- [ ] I can inspect an unfamiliar dataset.
- [ ] I can identify missing values.
- [ ] I can check duplicates.
- [ ] I can filter useful subsets.
- [ ] I can calculate group-wise statistics.
- [ ] I can explain the result instead of only producing code.